font:
  bold:
    family: Hurmit Nerd Font Mono
  italic:
    family: Hurmit Nerd Font Mono
  normal:
    family: Hurmit Nerd Font Mono
  offset:
    x: -1
    y: -4
  size: 9.5
window:
  opacity: 0.85
  padding:
    x: 2
    y: 2
window.opacity: 0.75
